# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2024 mwan3nft

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for mwan3nft
LUCI_DEPENDS:=+mwan3nft +luci-base
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-mwan3nft
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_LICENSE:=GPL-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildance
