#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# mwan3nft hotplug script for interface events

[ -z "$INTERFACE" ] && exit 0
[ "$ACTION" = "ifup" ] || [ "$ACTION" = "ifdown" ] || [ "$ACTION" = "ifupdate" ] || exit 0

. /lib/functions.sh
. /usr/lib/mwan3nft/common.sh

config_load mwan3nft

# Check if mwan3nft is enabled
enabled=$(uci -q get mwan3nft.globals.enabled)
[ "$enabled" = "0" ] && exit 0

# Check if this interface is managed by mwan3nft
is_mwan3nft_interface() {
	local iface="$1"
	local cfg_enabled

	config_get cfg_enabled "$iface" enabled 0
	[ "$cfg_enabled" = "1" ] && return 0
	return 1
}

# Only process interfaces managed by mwan3nft
is_mwan3nft_interface "$INTERFACE" || exit 0

mwan3nft_log "info" "Hotplug event: $ACTION on interface $INTERFACE"

case "$ACTION" in
	ifup)
		# Interface came up, update routing and rules
		/usr/sbin/mwan3nft ifup "$INTERFACE"
		;;
	ifdown)
		# Interface went down, update routing and rules
		/usr/sbin/mwan3nft ifdown "$INTERFACE"
		;;
	ifupdate)
		# Interface updated (e.g., IP changed), refresh rules
		/usr/sbin/mwan3nft ifupdate "$INTERFACE"
		;;
esac

exit 0
